---
dependency:
  name: galaxy
  enabled: true
  options:
    role-file: requirements.yml
driver:
  name: podman
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    privileged: true
    command: "/usr/sbin/init"
    tty: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
